# Generated by Django 6.0.6 on 2026-07-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LIBRARIAN', 'Librarian'), ('FACULTY', 'Faculty'), ('STUDENT', 'Student')], db_index=True, default='STUDENT', max_length=12),
        ),
    ]
