# Generated by Django 6.0.6 on 2026-07-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_faculty_id_seed_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
